.\" @(#)List.6 1.1 94/10/31 SMI
.if \n(zZ=1 .ig zZ
.TH LIST 6 "5 October 1989"
.SH LIST OF COMMANDS
.nf
.sp
.ta 20n; +20n
\fBName 	Appears on Page 	Description\fR
.sp
.zZ
\fBadventure\fP	\fBadventure\fP(6)	 an exploration game
\fBarithmetic\fP	\fBarithmetic\fP(6)	 provide drill in number facts
\fBbackgammon\fP	\fBbackgammon\fP(6)	 the game of backgammon
\fBbanner\fP	\fBbanner\fP(6)	 print large banner on printer
\fBbattlestar\fP	\fBbattlestar\fP(6)	 a tropical adventure game
\fBbcd\fP	\fBbcd\fP(6)	 convert to antique media
\fBbdemos\fP	\fBbdemos\fP(6)	 demonstrate Sun Monochrome Bitmap Display
\fBbdraw\fP	\fBdraw\fP(6)	 interactive graphics drawing
\fBbj\fP	\fBbj\fP(6)	 the game of black jack
\fBboggle\fP	\fBboggle\fP(6)	 play the game of boggle
\fBboggletool\fP	\fBboggletool\fP(6)	 play a game of boggle
\fBbouncedemo\fP	\fBgraphics_demos\fP(6)	 graphics demonstration programs
\fBbrotcube\fP	\fBbrotcube\fP(6)	 rotate a simple cube
\fBbsuncube\fP	\fBbsuncube\fP(6)	 view 3-D Sun logo
\fBbuttontest\fP	\fBbuttontest\fP(6)	 demonstration and testing program for SunButtons
\fBcanfield\fP	\fBcanfield\fP(6)	 Canfield solitaire card game
\fBcanfieldtool\fP	\fBcanfield\fP(6)	 Canfield solitaire card game
\fBcanvas_demo\fP	\fBsunview_demos\fP(6)	 Window-System demonstration programs
\fBcdplayer\fP	\fBcdplayer\fP(6)	 \s-1CD-ROM\s0 audio demo program
\fBcdraw\fP	\fBdraw\fP(6)	 interactive graphics drawing
\fBcfscores\fP	\fBcanfield\fP(6)	 Canfield solitaire card game
\fBchess\fP	\fBchess\fP(6)	 the game of chess
\fBchesstool\fP	\fBchesstool\fP(6)	 window-based front-end to chess program
\fBching\fP	\fBching\fP(6)	 the book of changes and other cookies
\fBcolordemos\fP	\fBcolordemos\fP(6)	 demonstrate Sun Color Graphics Display
\fBcraps\fP	\fBcraps\fP(6)	 the game of craps
\fBcribbage\fP	\fBcribbage\fP(6)	 the card game cribbage
\fBcursor_demo\fP	\fBsunview_demos\fP(6)	 Window-System demonstration programs
\fBdialtest\fP	\fBdialtest\fP(6)	 demonstration and testing program for SunDials
\fBdraw\fP	\fBdraw\fP(6)	 interactive graphics drawing
\fBfactor\fP	\fBfactor\fP(6)	 factor a number, generate large primes
\fBfish\fP	\fBfish\fP(6)	 play ``Go Fish''
\fBflight\fP	\fBgp_demos\fP(6)	 demonstration programs for the Graphics Processor
\fBfortune\fP	\fBfortune\fP(6)	 print a random, hopefully interesting, adage
\fBframedemo\fP	\fBgraphics_demos\fP(6)	 graphics demonstration programs
\fBgaintool\fP	\fBgaintool\fP(6)	 audio control panel
\fBgammontool\fP	\fBgammontool\fP(6)	 play a game of backgammon
\fBgp_demos\fP	\fBgp_demos\fP(6)	 demonstration programs for the Graphics Processor
\fBgraphics_demos\fP	\fBgraphics_demos\fP(6)	 graphics demonstration programs
\fBhack\fP	\fBhack\fP(6)	 replacement for rogue
\fBhangman\fP	\fBhangman\fP(6)	 computer version of the game hangman
\fBhunt\fP	\fBhunt\fP(6)	 a multiplayer multiterminal game
\fBjumpdemo\fP	\fBgraphics_demos\fP(6)	 graphics demonstration programs
\fBlife\fP	\fBlife\fP(6)	 John Conway's game of life
\fBmille\fP	\fBmille\fP(6)	 play Mille Bornes
\fBmonop\fP	\fBmonop\fP(6)	 Monopoly game
\fBmoo\fP	\fBmoo\fP(6)	 guessing game
\fBnumber\fP	\fBnumber\fP(6)	 convert Arabic numerals to English
\fBplay\fP	\fBplay\fP(6)	 play audio files
\fBppt\fP	\fBbcd\fP(6)	 convert to antique media
\fBprimes\fP	\fBfactor\fP(6)	 factor a number, generate large primes
\fBprimes\fP	\fBprimes\fP(6)	 print all primes larger than some given number
\fBquiz\fP	\fBquiz\fP(6)	 test your knowledge
\fBrain\fP	\fBrain\fP(6)	 animated raindrops display
\fBrandom\fP	\fBrandom\fP(6)	 select lines randomly from a file
\fBraw2audio\fP	\fBraw2audio\fP(6)	 convert raw audio data to audio file format
\fBrecord\fP	\fBrecord\fP(6)	 record an audio file
\fBrobots\fP	\fBrobots\fP(6)	 fight off villainous robots
\fBrotcvph\fP	\fBrotcvph\fP(6)	 rotate convex polyhedron
\fBrotobj\fP	\fBgp_demos\fP(6)	 demonstration programs for the Graphics Processor
\fBsnake\fP	\fBsnake\fP(6)	 display chase game
\fBsnscore\fP	\fBsnake\fP(6)	 display chase game
\fBsoundtool\fP	\fBsoundtool\fP(6)	 audio play/record tool
\fBspheresdemo\fP	\fBgraphics_demos\fP(6)	 graphics demonstration programs
\fBsuncoredemos\fP	\fBsuncoredemos\fP(6)	 demonstrate SunCore Graphics Package
\fBsunview_demos\fP	\fBsunview_demos\fP(6)	 Window-System demonstration programs
\fBtrek\fP	\fBtrek\fP(6)	 trekkie game
\fBvwcvph\fP	\fBvwcvph\fP(6)	 view convex polyhedron
\fBworm\fP	\fBworm\fP(6)	 play the growing worm game
\fBworms\fP	\fBworms\fP(6)	 animate worms on a display terminal
\fBwump\fP	\fBwump\fP(6)	 the game of hunt the wumpus
.fi
