.\" @(#)List.5 1.1 94/10/31 SMI
.if \n(zZ=1 .ig zZ
.TH LIST 5 "5 October 1989"
.SH LIST OF COMMANDS
.nf
.sp
.ta 20n; +20n
\fBName 	Appears on Page 	Description\fR
.sp
.zZ
\fBacct\fP	\fBacct\fP(5)	 execution accounting file
\fBaddresses\fP	\fBaliases\fP(5)	 addresses and aliases for sendmail
\fBaliases\fP	\fBaliases\fP(5)	 addresses and aliases for sendmail
\fBa.out\fP	\fBa.out\fP(5)	 assembler and link editor output format
\fBar\fP	\fBar\fP(5)	 archive (library) file format
\fBaudit_control\fP	\fBaudit_control\fP(5)	 control information for system audit daemon
\fBaudit_data\fP	\fBaudit_data\fP(5)	 current information on audit daemon
\fBaudit.log\fP	\fBaudit.log\fP(5)	 the security audit trail file
\fBauto.home\fP	\fBauto.home\fP(5)	 automount map for home directories
\fBauto.vol\fP	\fBauto.vol\fP(5)	 automount map for volumes
\fBbar\fP	\fBbar\fP(5)	 tape archive file format
\fBboards.pc\fP	\fBboards.pc\fP(5)	 \s-1AT\s0- and \s-1XT\s0-compatible boards for \s-1DOS\s0 windows
\fBbootparams\fP	\fBbootparams\fP(5)	 boot parameter data base
\fBbootservers\fP	\fBbootservers\fP(5)	 \s-1NIS\s0 bootservers file
\fBcoff\fP	\fBcoff\fP(5)	 common assembler and link editor output
\fBcore\fP	\fBcore\fP(5)	 format of memory image file
\fBcpio\fP	\fBcpio\fP(5)	 format of cpio archive
\fBcrontab\fP	\fBcrontab\fP(5)	 table of times to run periodic jobs
\fBdir\fP	\fBdir\fP(5)	 format of directories
\fBdump\fP	\fBdump\fP(5)	 incremental dump format
\fBdumpdates\fP	\fBdump\fP(5)	 incremental dump format
\fBenviron\fP	\fBenviron\fP(5V)	 user environment
\fBethers\fP	\fBethers\fP(5)	 Ethernet address to hostname database or \s-1NIS\s0 domain
\fBexports\fP	\fBexports\fP(5)	 directories to export to \s-1NFS\s0 clients
\fBext_ports\fP	\fBext_ports\fP(5)	 external ports file for network printers, terminals, and modems
\fBfbtab\fP	\fBfbtab\fP(5)	 framebuffer table
\fBfcntl\fP	\fBfcntl\fP(5)	 file control options
\fBfiletype\fP	\fBfiletype\fP(5)	 DeskSet binding database file
\fBforward\fP	\fBaliases\fP(5)	 addresses and aliases for sendmail
\fBfs\fP	\fBfs\fP(5)	 format of a 4.2 (ufs) file system volume
\fBfspec\fP	\fBfspec\fP(5)	 format specification in text files
\fBfstab\fP	\fBfstab\fP(5)	 static filesystem mounting table, mounted filesystems table
\fBftpusers\fP	\fBftpusers\fP(5)	 list of users prohibited by \s-1FTP\s0
\fBgettytab\fP	\fBgettytab\fP(5)	 terminal configuration data base
\fBgroup\fP	\fBgroup\fP(5)	 group file
\fBgroup.adjunct\fP	\fBgroup.adjunct\fP(5)	 group security data file
\fBhelp\fP	\fBhelp\fP(5)	 help file format
\fBhelp_viewer\fP	\fBhelp_viewer\fP(5)	 help viewer file format
\fBhosts\fP	\fBhosts\fP(5)	 host name data base
\fBhosts.equiv\fP	\fBhosts.equiv\fP(5)	 trusted hosts by system and by user
\fBindent.pro\fP	\fBindent.pro\fP(5)	 default options for indent
\fBinetd.conf\fP	\fBinetd.conf\fP(5)	 Internet servers database
\fBinode\fP	\fBfs\fP(5)	 format of a 4.2 (ufs) file system volume
\fBinternat\fP	\fBinternat\fP(5)	 key mapping table for internationalization
\fBipalloc.netrange\fP	\fBipalloc.netrange\fP(5)	 range of addresses to allocate
\fBkeytables\fP	\fBkeytables\fP(5)	 keyboard table descriptions for loadkeys and dumpkeys
\fBlastlog\fP	\fButmp\fP(5V)	 login records
\fBlink\fP	\fBlink\fP(5)	 link editor interfaces
\fBlocale\fP	\fBlocale\fP(5)	 locale database 
\fBmagic\fP	\fBmagic\fP(5)	 file command's magic number file
\fBmtab\fP	\fBfstab\fP(5)	 static filesystem mounting table, mounted filesystems table
\fBmtab\fP	\fBmtab\fP(5)	 mounted file system table
\fBnetgroup\fP	\fBnetgroup\fP(5)	 list of network groups
\fBnetmasks\fP	\fBnetmasks\fP(5)	 network mask data base
\fBnetrc\fP	\fBnetrc\fP(5)	 file for ftp remote login data
\fBnetworks\fP	\fBnetworks\fP(5)	 network name data base
\fBorgrc\fP	\fBorgrc\fP(5)	 organizer configuration and initialization file
\fBpasswd\fP	\fBpasswd\fP(5)	 password file
\fBpasswd.adjunct\fP	\fBpasswd.adjunct\fP(5)	 user security data file
\fBphones\fP	\fBphones\fP(5)	 remote host phone number data base
\fBplot\fP	\fBplot\fP(5)	 graphics interface
\fBpnp.sysnames\fP	\fBpnp.sysnames\fP(5)	 file used to allocate system names
\fBpolicies\fP	\fBpolicies\fP(5)	 network administration policies
\fBprintcap\fP	\fBprintcap\fP(5)	 printer capability data base
\fBproto\fP	\fBproto\fP(5)	 prototype job file for at
\fBprotocols\fP	\fBprotocols\fP(5)	 protocol name data base
\fBpublickey\fP	\fBpublickey\fP(5)	 public key database
\fBqueuedefs\fP	\fBqueuedefs\fP(5)	 queue description file for at, batch, and cron
\fBrasterfile\fP	\fBrasterfile\fP(5)	 Sun's file format for raster images
\fBremote\fP	\fBremote\fP(5)	 remote host description file
\fBresolv.conf\fP	\fBresolv.conf\fP(5)	 configuration file for domain name system resolver
\fBrfmaster\fP	\fBrfmaster\fP(5)	 Remote File Sharing name server master file
\fBrgb\fP	\fBrgb\fP(5)	 available colors (by name) for coloredit
\fBrhosts\fP	\fBhosts.equiv\fP(5)	 trusted hosts by system and by user
\fBrmtab\fP	\fBrmtab\fP(5)	 remote mounted file system table
\fBrootmenu\fP	\fBrootmenu\fP(5)	 root menu specification for SunView
\fBrpc\fP	\fBrpc\fP(5)	 rpc program number data base
\fBsccsfile\fP	\fBsccsfile\fP(5)	 format of an \s-1SCCS\s0 history file
\fBservices\fP	\fBservices\fP(5)	 Internet services and aliases
\fBsetup.pc\fP	\fBsetup.pc\fP(5)	 master configuration file for \s-1DOS\s0
\fBsm\fP	\fBsm\fP(5)	 in.statd directory and file structures
\fBsm\fP	\fBstatmon\fP(5)	 statd directories and file structures
\fBsm.bak\fP	\fBsm\fP(5)	 in.statd directory and file structures
\fBsm.bak\fP	\fBstatmon\fP(5)	 statd directories and file structures
\fBsm.state\fP	\fBsm\fP(5)	 in.statd directory and file structures
\fBstate\fP	\fBstatmon\fP(5)	 statd directories and file structures
\fBsunview\fP	\fBsunview\fP(5)	 initialization file for SunView
\fBsvdtab\fP	\fBsvdtab\fP(5)	 SunView device table
\fBsyslog.conf\fP	\fBsyslog.conf\fP(5)	 configuration file for syslogd system log daemon
\fBsystems\fP	\fBsystems\fP(5)	 \s-1NIS\s0 systems file
\fBtar\fP	\fBtar\fP(5)	 tape archive file format
\fBtermcap\fP	\fBtermcap\fP(5)	 terminal capability data base
\fBterm\fP	\fBterm\fP(5)	 terminal driving tables for nroff
\fBterm\fP	\fBterm\fP(5V)	 format of compiled term file
\fBterminfo\fP	\fBterminfo\fP(5V)	 terminal capability data base
\fBtoc\fP	\fBtoc\fP(5)	 table of contents of optional clusters
\fBtranslate\fP	\fBtranslate\fP(5)	 input and output files for system message translation
\fBttys\fP	\fBttytab\fP(5)	 terminal initialization data
\fBttytab\fP	\fBttytab\fP(5)	 terminal initialization data
\fBtypes\fP	\fBtypes\fP(5)	 primitive system data types
\fBtzfile\fP	\fBtzfile\fP(5)	 time zone information
\fBugid_alloc.range\fP	\fBugid_alloc.range\fP(5)	 range of user \s-1ID\s0s and group \s-1ID\s0s to allocate
\fBupdaters\fP	\fBupdaters\fP(5)	 configuration file for \s-1NIS\s0 updating
\fButmp\fP	\fButmp\fP(5V)	 login records
\fBuuencode\fP	\fBuuencode\fP(5)	 format of an encoded uuencode file
\fBvfont\fP	\fBvfont\fP(5)	 font formats
\fBvgrindefs\fP	\fBvgrindefs\fP(5)	 vgrind's language definition data base
\fBwtmp\fP	\fButmp\fP(5V)	 login records
\fBxtab\fP	\fBexports\fP(5)	 directories to export to \s-1NFS\s0 clients
\fBypaliases\fP	\fBypaliases\fP(5)	 \s-1NIS\s0 aliases for sendmail
\fBypfiles\fP	\fBypfiles\fP(5)	 \s-1NIS\s0 database and directory structure
\fBypgroup\fP	\fBypgroup\fP(5)	 \s-1NIS\s0 group file
\fByppasswd\fP	\fByppasswd\fP(5)	 \s-1NIS\s0 password file
\fBypprintcap\fP	\fBypprintcap\fP(5)	 \s-1NIS\s0 printer capability database
.fi
