.\" @(#)List.4 1.1 94/10/31 SMI
.if \n(zZ=1 .ig zZ
.TH LIST 4 "29 April 1992"
.SH LIST OF COMMANDS
.nf
.sp
.ta 20n; +20n
\fBName 	Appears on Page 	Description\fR
.sp
.zZ
\fBalm\fP	\fBmcp\fP(4S)	 \s-1ALM\s0-2 Asynchronous Line Multiplexer
\fBar\fP	\fBar\fP(4S)	 Archive 1/4 inch Streaming Tape Drive
\fBarp\fP	\fBarp\fP(4P)	 Address Resolution Protocol
\fBatbus\fP	\fBmem\fP(4S)	 main memory and bus I/O space
\fBaudio\fP	\fBaudio\fP(4)	 generic audio interface
\fBaudioamd\fP	\fBaudioand\fP(4)	 telephone quality audio device
\fBbpp\fP	\fBbpp\fP(4S)	bidirectional parallel port driver
\fBbwtwo\fP	\fBbwtwo\fP(4S)	 black and white memory frame buffer
\fBcdromio\fP	\fBcdromio\fP(4S)	 \s-1CDROM\s0 control operations
\fBcgeight\fP	\fBcgeight\fP(4S)	 24-bit color memory frame buffer
\fBcgfour\fP	\fBcgfour\fP(4S)	 Sun-3 color memory frame buffer
\fBcgnine\fP	\fBcgnine\fP(4S)	 24-bit \s-1VME\s0 color memory frame buffer
\fBcgsix\fP	\fBcgsix\fP(4S)	 accelerated 8-bit color frame buffer
\fBcgthree\fP	\fBcgthree\fP(4S)	 8-bit color memory frame buffer
\fBcgtwelve\fP	\fBcgtwelve\fP(4S)	 24-bit SBus color memory frame buffer
\fBcgtwo\fP	\fBcgtwo\fP(4S)	 color graphics interface
\fBconsole\fP	\fBconsole\fP(4S)	 console driver and terminal emulator
\fBdb\fP	\fBdb\fP(4M)	 SunDials \s-1STREAMS\s0 module
\fBdbri\fP	\fBdbri\fP(4)	 Dual Basic Rate ISDN Interface and SpeakerBox controller
\fBdes\fP	\fBdes\fP(4S)	 \s-1DES\s0 encryption chip interface
\fBdkio\fP	\fBdkio\fP(4S)	 generic disk control operations
\fBdrum\fP	\fBdrum\fP(4)	 paging device
\fBeeprom\fP	\fBmem\fP(4S)	 main memory and bus I/O space
\fBfb\fP	\fBfb\fP(4S)	 driver for Sun console frame buffer
\fBfbio\fP	\fBfbio\fP(4S)	 frame buffer control operations
\fBfd\fP	\fBfd\fP(4S)	 Disk driver for Floppy Disk Controllers
\fBfilio\fP	\fBfilio\fP(4)	 ioctls that operate directly on files, file descriptors, and sockets
\fBfpa\fP	\fBfpa\fP(4S)	 Sun-3 floating-point accelerator
\fBgpone\fP	\fBgpone\fP(4S)	 graphics processor
\fBgt\fP	\fBgt\fP(4S)	 double buffered 24-bit SBus graphics accelerator
\fBicmp\fP	\fBicmp\fP(4P)	 Internet Control Message Protocol
\fBid\fP	\fBid\fP(4S)	 disk driver for IPI disk controllers
\fBie\fP	\fBie\fP(4S)	 Intel 10 Mb/s Ethernet interface
\fBif\fP	\fBif\fP(4N)	 general properties of network interfaces
\fBinet\fP	\fBinet\fP(4F)	 Internet protocol family
\fBip\fP	\fBip\fP(4P)	 Internet Protocol
\fBipi\fP	\fBipi\fP(4S)	 IPI driver
\fBis\fP	\fBis\fP(4S)	 IPI channel driver for Sun IPI string controllers
\fBkb\fP	\fBkb\fP(4M)	 Sun keyboard \s-1STREAMS\s0 module
\fBkbd\fP	\fBkbd\fP(4S)	 Sun keyboard
\fBkmem\fP	\fBmem\fP(4S)	 main memory and bus I/O space
\fBldterm\fP	\fBldterm\fP(4M)	 standard terminal \s-1STREAMS\s0 module
\fBle\fP	\fBle\fP(4S)	 \s-1LANCE\s0 10Mb/s Ethernet interface
\fBlo\fP	\fBlo\fP(4N)	 software loopback network interface
\fBlofs\fP	\fBlofs\fP(4S)	 loopback virtual file system
\fBmcp\fP	\fBmcp\fP(4S)	 \s-1MCP\s0 Multiprotocol Communications Processor
\fBmem\fP	\fBmem\fP(4S)	 main memory and bus I/O space
\fBmouse\fP	\fBmouse\fP(4S)	 Sun mouse
\fBms\fP	\fBms\fP(4M)	 Sun mouse \s-1STREAMS\s0 module
\fBmti\fP	\fBmti\fP(4S)	 Systech \s-1MTI\s0-800/1600 multi-terminal interface
\fBmtio\fP	\fBmtio\fP(4)	 general magnetic tape interface
\fBNFS\fP	\fBnfs\fP(4P)	 network file system
\fBnit\fP	\fBnit\fP(4P)	 Network Interface Tap
\fBnit_buf\fP	\fBnit_buf\fP(4M)	 \s-1STREAMS NIT\s0 buffering module
\fBnit_if\fP	\fBnit_if\fP(4M)	 \s-1STREAMS NIT\s0 device interface module
\fBnif_pf\fP	\fBnit_pf\fP(4M)	 \s-1STREAMS NIT\s0 packet filtering module
\fBnull\fP	\fBnull\fP(4)	 data sink
\fBopenprom\fP	\fBopenprom\fP(4S)	 \s-1PROM\s0 monitor configuration interface
\fBpp\fP	\fBpp\fP(4 )	 Centronics-compatible parallel printer port
\fBpty\fP	\fBpty\fP(4)	 pseudo-terminal driver
\fBrfs\fP	\fBrfs\fP(4)	 remote file sharing service
\fBroot\fP	\fBroot\fP(4S)	 pseudo-driver for Sun386i root disk
\fBrouting\fP	\fBrouting\fP(4N)	 system supporting for local network packet routing
\fBsbus\fP	\fBmem\fP(4S)	 main memory and bus I/O space
\fBsd\fP	\fBsd\fP(4S)	 driver for \s-1SCSI\s0 disk devices
\fBsockio\fP	\fBsockio\fP(4)	 ioctls that operate directly on sockets
\fBsr\fP	\fBsr\fP(4S)	 driver for \s-1CDROM SCSI\s0 controller
\fBst\fP	\fBst\fP(4S)	 driver for \s-1SCSI\s0 tape devices
\fBstreamio\fP	\fBstreamio\fP(4)	 \s-1STREAMS\s0 ioctl commands
\fBtaac\fP	\fBtaac\fP(4S)	 Sun applications accelerator
\fBtcp\fP	\fBtcp\fP(4P)	 Internet Transmission Control Protocol
\fBtcptli\fP	\fBtcptli\fP(4P)	 \s-1TLI\s0-Conforming \s-1TCP\s0 Stream-Head
\fBtermio\fP	\fBtermio\fP(4)	 general terminal interface
\fBtfs\fP	\fBtfs\fP(4S)	 translucent file service
\fBtm\fP	\fBtm\fP(4S)	 Tapemaster 1/2 inch tape controller
\fBtmpfs\fP	\fBtmpfs\fP(4S)	 memory based filesystem
\fBttcompat\fP	\fBttcompat\fP(4M)	 V7 and 4\s-1BSD STREAMS\s0 compatibility module
\fBtty\fP	\fBtty\fP(4)	 controlling terminal interface
\fBudp\fP	\fBudp\fP(4P)	 Internet User Datagram Protocol
\fBunix\fP	\fBunix\fP(4F)	 \s-1UNIX\s0 domain protocol family
\fBvd\fP	\fBvd\fP(4)	 loadable modules interface
\fBvme16d16\fP	\fBmem\fP(4S)	 main memory and bus I/O space
\fBvme16d32\fP	\fBmem\fP(4S)	 main memory and bus I/O space
\fBvme24d16\fP	\fBmem\fP(4S)	 main memory and bus I/O space
\fBvme24d32\fP	\fBmem\fP(4S)	 main memory and bus I/O space
\fBvme32d16\fP	\fBmem\fP(4S)	 main memory and bus I/O space
\fBvme32d32\fP	\fBmem\fP(4S)	 main memory and bus I/O space
\fBvpc\fP	\fBvpc\fP(4S)	 Systech \s-1VPC\s0-2200 Versatec printer/plotter
\fBvx\fP	\fBvx\fP(4S)	 Sun applications accelerator
\fBwin\fP	\fBwin\fP(4S)	 Sun window system
\fBxd\fP	\fBxd\fP(4S)	 Disk driver for Xylogics 7053 \s-1SMD\s0 Disk Controller
\fBxt\fP	\fBxt\fP(4S)	 Xylogics 472 1/2 inch tape controller
\fBxy\fP	\fBxy\fP(4S)	 Disk driver for Xylogics 450 and 451 \s-1SMD\s0 Disk Controllers
\fBzero\fP	\fBmem\fP(4S)	 main memory and bus I/O space
\fBzero\fP	\fBzero\fP(4S)	 source of zeroes
\fBzs\fP	\fBzs\fP(4S)	 Zilog 8530 \s-1SCC\s0 serial communications driver
.fi
